In [2]:
# Impotamos las lbrerias necesarias
import numpy as np
import math as mt
import matplotlib.pyplot as plt
import pandas as pd
import requests
import os
import unidecode

In [49]:
import requests
import json

# Su clave de API de Google Maps
api_key = 'AIzaSyDByTkYo_aCRRrh8w6tPsRIoZohcVcAZpc'

# El código postal que desea buscar
codigo_postal = '37230'

# Crear la URL de la solicitud
url = 'https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}'.format(codigo_postal, api_key)

# Enviar la solicitud
response = requests.get(url)

# Procesar la respuesta
data = json.loads(response.text)

# Mostrar la dirección completa
print(data['results'][0]['formatted_address'])

IndexError: list index out of range

In [50]:
import requests
import csv

# Su clave de API de Google Maps
api_key = 'AIzaSyDByTkYo_aCRRrh8w6tPsRIoZohcVcAZpc'

# La lista de códigos postales
codigos_postales = ['11000', '11100', '11200', '11300']

# Crear un archivo CSV para guardar la información
with open('ubicaciones.csv', 'w', newline='') as csvfile:
    fieldnames = ['codigo_postal', 'latitud', 'longitud']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    
    # Iterar sobre cada código postal
    for codigo_postal in codigos_postales:
        # Crear la URL de la solicitud
        url = 'https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}'.format(codigo_postal, api_key)

        # Enviar la solicitud
        response = requests.get(url)

        # Procesar la respuesta
        data = response.json()

        # Obtener la latitud y longitud
        latitud = data['results'][0]['geometry']['location']['lat']
        longitud = data['results'][0]['geometry']['location']['lng']

        # Guardar la información en el archivo CSV
        writer.writerow({'codigo_postal': codigo_postal, 'latitud': latitud, 'longitud': longitud})

IndexError: list index out of range

In [4]:
path = f'/home/luiscantero/Hola/Python/Google_Earth_API/data/Book1.csv'
tabla1 = pd.read_csv(path)

In [5]:
tabla1['d_codigo'][0]

1000

In [6]:
tabla1

,d_codigo,d_asenta,D_mnpio,d_estado,d_ciudad
0,1000,San Ángel,Álvaro Obregón,Ciudad de México,Ciudad de México
1,1010,Los Alpes,Álvaro Obregón,Ciudad de México,Ciudad de México
2,1020,Guadalupe Inn,Álvaro Obregón,Ciudad de México,Ciudad de México
3,1030,Axotla,Álvaro Obregón,Ciudad de México,Ciudad de México
4,1030,Florida,Álvaro Obregón,Ciudad de México,Ciudad de México
...,...,...,...,...,...
151520,99994,Vicente Guerrero,Moyahua de Estrada,Zacatecas,NaN
151521,99997,Las Palmas,Moyahua de Estrada,Zacatecas,NaN
151522,99998,El Limón,Moyahua de Estrada,Zacatecas,NaN
151523,99998,Jesús Maria,Moyahua de Estrada,Zacatecas,NaN
151524,99998,Palmarejo,Moyahua de Estrada,Zacatecas,NaN

In [7]:
tabla1.columns

Index(['d_codigo', 'd_asenta', 'D_mnpio', 'd_estado', 'd_ciudad'], dtype='object')

In [8]:
np.shape(tabla1)

(151525, 5)

In [9]:
# d_codigo : contiene el codigo postal
# d_asenta : el nombre de la colonia
# D_mnpio : el nombre del municipio
# d_estado : el nombre del estado

In [10]:


path = f'/home/luiscantero/Hola/Python/Google_Earth_API/ventas/'
frames = []

for file in os.listdir(path):
    if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(path, file))
        df = df.loc[(df['Buyer Currency'] == 'MXN')]
        #df = df.dropna()
        #df['Buyer Postal Code'] = df['Buyer Postal Code'].apply(lambda x: x.zfill(5))
        frames.append(df[["Buyer Postal Code","Buyer Currency"]])

result = pd.concat(frames)

In [11]:
result.reset_index(drop=True, inplace=True)

In [12]:
result.shape

(3253, 2)

In [13]:
result = result.dropna()

In [14]:
if result.isnull().any().any():
    print("La tabla tiene valores nulos.")
else:
    print("La tabla no tiene valores nulos.")

La tabla no tiene valores nulos.

In [27]:
def check_int(val):
    if type(val) != int:
        return False
    return True

if result['Buyer Postal Code'].apply(check_int).any() == False:
    print("La columna contiene valores que no son int.")
else:
    print("La columna solo contiene valores int.")

La columna solo contiene valores int.

In [16]:
result["colonia"] = None
result["municipio"] = None
result["estado"] = None
result

     Buyer Postal Code Buyer Currency colonia municipio estado
0                37520            MXN    None      None   None
1                37520            MXN    None      None   None
2                37530            MXN    None      None   None
3                37530            MXN    None      None   None
4                37230            MXN    None      None   None
...                ...            ...     ...       ...    ...
3248             77518            MXN    None      None   None
3249             77518            MXN    None      None   None
3250             79610            MXN    None      None   None
3251             79610            MXN    None      None   None
3252             79610            MXN    None      None   None

[3232 rows x 5 columns]

In [36]:
len(result["Buyer Postal Code"])

3232

In [ ]:
for index in range(0, len(result["Buyer Postal Code"])):
    print(index, end="\r")
    
    
    for j in range(0, len(tabla1["d_codigo"])):
        
    
        try:
            
            if (result["Buyer Postal Code"][index] == tabla1["d_codigo"][j]):
                #print(tabla1["d_asenta"][j])
                result["colonia"][index] = tabla1["d_asenta"][j]
                result["municipio"][index] = tabla1["D_mnpio"][j]
                result["estado"][index] = tabla1["d_estado"][j]
                break
        except: print("erroren :" + str(index))

In [29]:
result["direccion"] = None

In [37]:
result

,Buyer Postal Code,Buyer Currency,colonia,municipio,estado,direccion
0,37520,MXN,Aztecas,León,Guanajuato,"Aztecas, León, Guanajuato"
1,37520,MXN,Aztecas,León,Guanajuato,"Aztecas, León, Guanajuato"
2,37530,MXN,Cerrito de Jerez,León,Guanajuato,"Cerrito de Jerez, León, Guanajuato"
3,37530,MXN,Cerrito de Jerez,León,Guanajuato,"Cerrito de Jerez, León, Guanajuato"
4,37230,MXN,Jardines de Providencia,León,Guanajuato,"Jardines de Providencia, León, Guanajuato"
...,...,...,...,...,...,...
3248,77518,MXN,None,None,None,None
3249,77518,MXN,None,None,None,None
3250,79610,MXN,None,None,None,None
3251,79610,MXN,None,None,None,None
3252,79610,MXN,None,None,None,None

In [38]:
index = 0
result["colonia"][index] + ", " + result["municipio"][index] + ", " + result["estado"][index]

'Aztecas, León, Guanajuato'

In [39]:
for index in range(0, len(result["Buyer Postal Code"])):
    try:
        nombre = result["colonia"][index] + ", " + result["municipio"][index] + ", " + result["estado"][index]
        result["direccion"][index] = nombre 
    except: print("Error en: " + str(index))

Error en: 46
Error en: 47
Error en: 48
Error en: 49
Error en: 164
Error en: 165
Error en: 166
Error en: 167
Error en: 202
Error en: 203
Error en: 266
Error en: 267
Error en: 268
Error en: 269
Error en: 270
Error en: 271
Error en: 272
Error en: 273
Error en: 274
Error en: 275
Error en: 276
Error en: 277
Error en: 278
Error en: 279
Error en: 280
Error en: 281
Error en: 282
Error en: 283
Error en: 284
Error en: 285
Error en: 286
Error en: 287
Error en: 288
Error en: 289
Error en: 290
Error en: 291
Error en: 292
Error en: 293
Error en: 294
Error en: 295
Error en: 296
Error en: 297
Error en: 298
Error en: 299
Error en: 300
Error en: 301
Error en: 302
Error en: 303
Error en: 304
Error en: 305
Error en: 306
Error en: 307
Error en: 308
Error en: 309
Error en: 310
Error en: 311
Error en: 312
Error en: 313
Error en: 314
Error en: 315
Error en: 316
Error en: 317
Error en: 318
Error en: 319
Error en: 320
Error en: 321
Error en: 322
Error en: 323
Error en: 324
Error en: 325
Error en: 326
Error en: 327
Error en: 328
Error en: 329
Error en: 330
Error en: 331
Error en: 332
Error en: 333
Error en: 334
Error en: 335
Error en: 336
Error en: 337
Error en: 338
Error en: 339
Error en: 340
Error en: 341
Error en: 342
Error en: 343
Error en: 344
Error en: 345
Error en: 346
Error en: 347
Error en: 348
Error en: 349
Error en: 350
Error en: 351
Error en: 352
Error en: 353
Error en: 354
Error en: 355
Error en: 356
Error en: 357
Error en: 358
Error en: 359
Error en: 360
Error en: 361
Error en: 362
Error en: 363
Error en: 364
Error en: 365
Error en: 366
Error en: 367
Error en: 368
Error en: 369
Error en: 370
Error en: 371
Error en: 372
Error en: 373
Error en: 374
Error en: 375
Error en: 376
Error en: 377
Error en: 378
Error en: 379
Error en: 380
Error en: 381
Error en: 382
Error en: 383
Error en: 384
Error en: 385
Error en: 386
Error en: 387
Error en: 388
Error en: 389
Error en: 390
Error en: 391
Error en: 392
Error en: 393
Error en: 394
Error en: 395
Error en: 396
Error en: 397
Error en: 398
Error en: 399
Error en: 400
Error en: 401
Error en: 402
Error en: 403
Error en: 404
Error en: 405
Error en: 406
Error en: 407
Error en: 408
Error en: 409
Error en: 410
Error en: 411
Error en: 412
Error en: 413
Error en: 414
Error en: 415
Error en: 416
Error en: 417
Error en: 418
Error en: 419
Error en: 516
Error en: 517
Error en: 538
Error en: 539
Error en: 552
Error en: 553
Error en: 564
Error en: 565
Error en: 614
Error en: 615
Error en: 648
Error en: 649
Error en: 658
Error en: 659
Error en: 760
Error en: 761
Error en: 812
Error en: 813
Error en: 874
Error en: 875
Error en: 876
Error en: 877
Error en: 878
Error en: 879
Error en: 880
Error en: 881
Error en: 882
Error en: 883
Error en: 884
Error en: 885
Error en: 886
Error en: 887
Error en: 888
Error en: 889
Error en: 890
Error en: 891
Error en: 892
Error en: 893
Error en: 894
Error en: 895
Error en: 896
Error en: 897
Error en: 898
Error en: 899
Error en: 900
Error en: 901
Error en: 902
Error en: 903
Error en: 904
Error en: 905
Error en: 906
Error en: 907
Error en: 908
Error en: 909
Error en: 910
Error en: 911
Error en: 912
Error en: 913
Error en: 914
Error en: 915
Error en: 916
Error en: 917
Error en: 918
Error en: 919
Error en: 920
Error en: 921
Error en: 1060
Error en: 1061
Error en: 1062
Error en: 1063
Error en: 1064
Error en: 1065
Error en: 1066
Error en: 1067
Error en: 1068
Error en: 1069
Error en: 1070
Error en: 1071
Error en: 1072
Error en: 1073
Error en: 1074
Error en: 1075
Error en: 1076
Error en: 1077
Error en: 1078
Error en: 1079
Error en: 1080
Error en: 1081
Error en: 1082
Error en: 1083
Error en: 1084
Error en: 1085
Error en: 1150
Error en: 1151
Error en: 1340
Error en: 1341
Error en: 1378
Error en: 1379
Error en: 1380
Error en: 1381
Error en: 1382
Error en: 1383
Error en: 1390
Error en: 1391
Error en: 1428
Error en: 1429
Error en: 1560
Error en: 1561
Error en: 1578
Error en: 1579
Error en: 1604
Error en: 1605
Error en: 1612
Error en: 1613
Error en: 1614
Error en: 1615
Error en: 1658
Error en: 1659
Error en: 1660
Error en: 1661
Error en: 1680
Error en: 1681
Error en: 1730
Error en: 1731
Error en: 1732
Error en: 1733
Error en: 1790
Error en: 1791
Error en: 1812
Error en: 1813
Error en: 1814
Error en: 1815
Error en: 1816
Error en: 1817
Error en: 1874
Error en: 1875
Error en: 1876
Error en: 1877
Error en: 1982
Error en: 1983
Error en: 1984
Error en: 1985
Error en: 2104
Error en: 2105
Error en: 2106
Error en: 2107
Error en: 2108
Error en: 2109
Error en: 2110
Error en: 2111
Error en: 2112
Error en: 2113
Error en: 2114
Error en: 2115
Error en: 2151
Error en: 2170
Error en: 2195
Error en: 2205
Error en: 2359
Error en: 2366
Error en: 2367
Error en: 2374
Error en: 2378
Error en: 2418
Error en: 2470
Error en: 2471
Error en: 2472
Error en: 2542
Error en: 2627
Error en: 2628
Error en: 2629
Error en: 2630
Error en: 2631
Error en: 2632
Error en: 2633
Error en: 2634
Error en: 2635
Error en: 2636
Error en: 2637
Error en: 2638
Error en: 2639
Error en: 2640
Error en: 2641
Error en: 2642
Error en: 2643
Error en: 2644
Error en: 2645
Error en: 2646
Error en: 2647
Error en: 2648
Error en: 2649
Error en: 2650
Error en: 2651
Error en: 2652
Error en: 2653
Error en: 2654
Error en: 2655
Error en: 2656
Error en: 2657
Error en: 2658
Error en: 2659
Error en: 2660
Error en: 2661
Error en: 2662
Error en: 2663
Error en: 2664
Error en: 2665
Error en: 2666
Error en: 2667
Error en: 2668
Error en: 2669
Error en: 2670
Error en: 2671
Error en: 2672
Error en: 2673
Error en: 2674
Error en: 2675
Error en: 2676
Error en: 2677
Error en: 2678
Error en: 2679
Error en: 2680
Error en: 2681
Error en: 2682
Error en: 2683
Error en: 2684
Error en: 2685
Error en: 2686
Error en: 2687
Error en: 2688
Error en: 2734
Error en: 2735
Error en: 2736
Error en: 2737
Error en: 2738
Error en: 2739
Error en: 2743
Error en: 2766
Error en: 2767
Error en: 2771
Error en: 2785
Error en: 2786
Error en: 2787
Error en: 2788
Error en: 2789
Error en: 2838
Error en: 2869
Error en: 2873
Error en: 2892
Error en: 2893
Error en: 2894
Error en: 2895
Error en: 2896
Error en: 2897
Error en: 2898
Error en: 2899
Error en: 2900
Error en: 2901
Error en: 2902
Error en: 2903
Error en: 2904
Error en: 2905
Error en: 2906
Error en: 2907
Error en: 2908
Error en: 2909
Error en: 2910
Error en: 2911
Error en: 2912
Error en: 2913
Error en: 2914
Error en: 2915
Error en: 2916
Error en: 2917
Error en: 2918
Error en: 2919
Error en: 2920
Error en: 2921
Error en: 2922
Error en: 2923
Error en: 2924
Error en: 2925
Error en: 2926
Error en: 2927
Error en: 2928
Error en: 2929
Error en: 2930
Error en: 2931
Error en: 2932
Error en: 2933
Error en: 2934
Error en: 2935
Error en: 2936
Error en: 2937
Error en: 2938
Error en: 2939
Error en: 2940
Error en: 2941
Error en: 2942
Error en: 2943
Error en: 2944
Error en: 2945
Error en: 2946
Error en: 2947
Error en: 2948
Error en: 2952
Error en: 2953
Error en: 2978
Error en: 3012
Error en: 3022
Error en: 3026
Error en: 3030
Error en: 3031
Error en: 3032
Error en: 3033
Error en: 3034
Error en: 3035
Error en: 3048
Error en: 3073
Error en: 3074
Error en: 3084

In [40]:
result

,Buyer Postal Code,Buyer Currency,colonia,municipio,estado,direccion
0,37520,MXN,Aztecas,León,Guanajuato,"Aztecas, León, Guanajuato"
1,37520,MXN,Aztecas,León,Guanajuato,"Aztecas, León, Guanajuato"
2,37530,MXN,Cerrito de Jerez,León,Guanajuato,"Cerrito de Jerez, León, Guanajuato"
3,37530,MXN,Cerrito de Jerez,León,Guanajuato,"Cerrito de Jerez, León, Guanajuato"
4,37230,MXN,Jardines de Providencia,León,Guanajuato,"Jardines de Providencia, León, Guanajuato"
...,...,...,...,...,...,...
3248,77518,MXN,None,None,None,None
3249,77518,MXN,None,None,None,None
3250,79610,MXN,None,None,None,None
3251,79610,MXN,None,None,None,None
3252,79610,MXN,None,None,None,None

In [47]:
np.shape(result.dropna())

(2747, 6)

In [43]:


result = result.applymap(lambda s: unidecode.unidecode(s) if type(s) == str else s)
result.iloc[0:len(result["Buyer Postal Code"])].to_csv('resultados_finales_dic_2022_v2.csv', index=False)

In [48]:
result = result.applymap(lambda s: unidecode.unidecode(s) if type(s) == str else s)
result.dropna().iloc[0:len(result["Buyer Postal Code"])].to_csv('resultados_finales_dic_2022_v2.csv', index=False)